<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.ncu.csh</groupId>
        <artifactId>HealthSystem</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>health-checkgroup</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <dependency>
            <groupId>com.ncu.csh</groupId>
            <artifactId>health-common</artifactId>
        </dependency>
        <!-- 检查组勾选检查项时使用 CheckItemDAO -->
        <dependency>
            <groupId>com.ncu.csh</groupId>
            <artifactId>health-checkitem</artifactId>
        </dependency>
    </dependencies>
</project>
